let btns = [
  ["Secondary First Year", "1"],
  ["Secondary Second Year", "2"],
  ["Secondary Third Year", "3"],
  ["Secondary Fourth Year", "4"],
  ["Secondary Final Year", "5"],
  ["Senior Secondary First Year", "6"],
  ["Senior Secondary Final Year", "7"],
  ["Degree First Year", "8"],
  ["Degree Second Year", "9"],
  ["Degree Final Year", "10"],
];
const filterButton = () => {
  let container = document.querySelector(".filterButtons");
  for (let i = 0; i < btns.length; i++) {
    container.insertAdjacentHTML(
      "beforeend",
      `<li class="${btns[i][0].replaceAll(" ", "-")}" onclick="filterData('${
        btns[i][0]
      }')">${btns[i][1]}</li>`
    );
  }
};

let studentData = [
  {
    adNo: 3901,
    name: "Muhammed Najah P",
    section: "Secondary First Year",
    memNo: "30/383901",
    memType: "Passive",
  },
  {
    adNo: 3918,
    name: "Muhamed Shafeeh K",
    section: "Secondary First Year",
    memNo: "30/383918",
    memType: "Passive",
  },
  {
    adNo: 3903,
    name: "Muhammed Sinan P",
    section: "Secondary First Year",
    memNo: "30/383903",
    memType: "Passive",
  },
  {
    adNo: 3944,
    name: "Mohammed Anas .V.P",
    section: "Secondary First Year",
    memNo: "30/383944",
    memType: "Passive",
  },
  {
    adNo: 3905,
    name: "Mufeed. K",
    section: "Secondary First Year",
    memNo: "30/383905",
    memType: "Passive",
  },
  {
    adNo: 3921,
    name: "Muhammed Musthafa. K",
    section: "Secondary First Year",
    memNo: "30/383921",
    memType: "Passive",
  },
  {
    adNo: 3916,
    name: "Adhil Salah",
    section: "Secondary First Year",
    memNo: "30/383916",
    memType: "Passive",
  },
  {
    adNo: 3913,
    name: "Muhammed Hashir",
    section: "Secondary First Year",
    memNo: "30/383913",
    memType: "Passive",
  },
  {
    adNo: 3908,
    name: "Muhammede Adhin Kp",
    section: "Secondary First Year",
    memNo: "30/383908",
    memType: "Passive",
  },
  {
    adNo: 3912,
    name: "Muhammed Hasan Gazali",
    section: "Secondary First Year",
    memNo: "30/383912",
    memType: "Passive",
  },
  {
    adNo: 3902,
    name: "Sahil Abdul Shukkur",
    section: "Secondary First Year",
    memNo: "30/383902",
    memType: "Passive",
  },
  {
    adNo: 3947,
    name: "Muhammed Riyan",
    section: "Secondary First Year",
    memNo: "30/383947",
    memType: "Passive",
  },
  {
    adNo: 3926,
    name: "Nihal Ibraheem V T",
    section: "Secondary First Year",
    memNo: "30/383926",
    memType: "Passive",
  },
  {
    adNo: 3899,
    name: "Muhammad Shafin",
    section: "Secondary First Year",
    memNo: "30/383899",
    memType: "Passive",
  },
  {
    adNo: 3907,
    name: "Muhammed Nishal",
    section: "Secondary First Year",
    memNo: "30/383907",
    memType: "Passive",
  },
  {
    adNo: 3936,
    name: "Habeeburahman",
    section: "Secondary First Year",
    memNo: "30/383936",
    memType: "Passive",
  },
  {
    adNo: 3910,
    name: "Muhamed Ashfaq P P",
    section: "Secondary First Year",
    memNo: "30/383910",
    memType: "Passive",
  },
  {
    adNo: 3906,
    name: "Mohamed Nabeel. Vp",
    section: "Secondary First Year",
    memNo: "30/383906",
    memType: "Passive",
  },
  {
    adNo: 3937,
    name: "Faslurahman P",
    section: "Secondary First Year",
    memNo: "30/383937",
    memType: "Passive",
  },
  {
    adNo: 3909,
    name: "Muhammed Adil M",
    section: "Secondary First Year",
    memNo: "30/383909",
    memType: "Passive",
  },
  {
    adNo: 3935,
    name: "Muhammed Hanoon",
    section: "Secondary First Year",
    memNo: "30/383935",
    memType: "Passive",
  },
  {
    adNo: 3919,
    name: "Amish Ibrahim",
    section: "Secondary First Year",
    memNo: "30/383919",
    memType: "Passive",
  },
  {
    adNo: 3904,
    name: "Muhammed Hisham Tc",
    section: "Secondary First Year",
    memNo: "30/383904",
    memType: "Passive",
  },
  {
    adNo: 3929,
    name: "Muhammad Abshaar",
    section: "Secondary First Year",
    memNo: "30/383929",
    memType: "Passive",
  },
  {
    adNo: 3945,
    name: "Hadi Hamdan C.T",
    section: "Secondary First Year",
    memNo: "30/383945",
    memType: "Passive",
  },
  {
    adNo: 3900,
    name: "Mohammed Shabil. P",
    section: "Secondary First Year",
    memNo: "30/383900",
    memType: "Passive",
  },
  {
    adNo: 3932,
    name: "Muhammad Sidan",
    section: "Secondary First Year",
    memNo: "30/383932",
    memType: "Passive",
  },
  {
    adNo: 3922,
    name: "Mohammed Niyas",
    section: "Secondary First Year",
    memNo: "30/383922",
    memType: "Passive",
  },
  {
    adNo: 3942,
    name: "Muhammed Razin Kk",
    section: "Secondary First Year",
    memNo: "30/383942",
    memType: "Passive",
  },
  {
    adNo: 3934,
    name: "Muhammed Shammas Ct",
    section: "Secondary First Year",
    memNo: "30/383934",
    memType: "Passive",
  },
  {
    adNo: 3931,
    name: "Saiful Bari P",
    section: "Secondary First Year",
    memNo: "30/383931",
    memType: "Passive",
  },
  {
    adNo: 3930,
    name: "Muhammed Amjad",
    section: "Secondary First Year",
    memNo: "30/383930",
    memType: "Passive",
  },
  {
    adNo: 3917,
    name: "Muhammed Jabir .Vp",
    section: "Secondary First Year",
    memNo: "30/383917",
    memType: "Passive",
  },
  {
    adNo: 3915,
    name: "Muhammed Aflah Cp",
    section: "Secondary First Year",
    memNo: "30/383915",
    memType: "Passive",
  },
  {
    adNo: 3928,
    name: "Muhammed Faheem",
    section: "Secondary First Year",
    memNo: "30/383928",
    memType: "Passive",
  },
  {
    adNo: 3911,
    name: "Razal .K",
    section: "Secondary First Year",
    memNo: "30/383911",
    memType: "Passive",
  },
  {
    adNo: 3923,
    name: "Muhammed Sinan K.P",
    section: "Secondary First Year",
    memNo: "30/383923",
    memType: "Passive",
  },
  {
    adNo: 3914,
    name: "Muhammed Aflah V",
    section: "Secondary First Year",
    memNo: "30/383914",
    memType: "Passive",
  },
  {
    adNo: 3933,
    name: "Muhammed Nabeel.Kp",
    section: "Secondary First Year",
    memNo: "30/383933",
    memType: "Passive",
  },
  {
    adNo: 3924,
    name: "Ameen Abdul Hameed",
    section: "Secondary First Year",
    memNo: "30/383924",
    memType: "Passive",
  },
  {
    adNo: 3940,
    name: "Muhammad Naeem",
    section: "Secondary First Year",
    memNo: "30/383940",
    memType: "Passive",
  },
  {
    adNo: 3920,
    name: "Fahim",
    section: "Secondary First Year",
    memNo: "30/383920",
    memType: "Passive",
  },
  {
    adNo: 3938,
    name: "Ashmil Mk",
    section: "Secondary First Year",
    memNo: "30/383938",
    memType: "Passive",
  },
  {
    adNo: 3927,
    name: "Muhammed Shamil M",
    section: "Secondary First Year",
    memNo: "30/383927",
    memType: "Passive",
  },
  {
    adNo: 3939,
    name: "Muhammed Nadir. C",
    section: "Secondary First Year",
    memNo: "30/383939",
    memType: "Passive",
  },
  {
    adNo: 3941,
    name: "Abdulla.T",
    section: "Secondary First Year",
    memNo: "30/383941",
    memType: "Passive",
  },
  {
    adNo: 3946,
    name: "Mohammed Sinan",
    section: "Secondary First Year",
    memNo: "30/383946",
    memType: "Passive",
  },
  {
    adNo: 3925,
    name: "Mohammed Nasif.T",
    section: "Secondary First Year",
    memNo: "30/383925",
    memType: "Passive",
  },
  {
    adNo: 3943,
    name: "Anoos A",
    section: "Secondary First Year",
    memNo: "30/383943",
    memType: "Passive",
  },
  {
    adNo: 3877,
    name: "Amjad Pc &nbsp;",
    section: "Secondary First Year",
    memNo: "30/383877",
    memType: "Passive",
  },
  {
    adNo: 3871,
    name: "Aban Atif &nbsp;",
    section: "Secondary First Year",
    memNo: "30/383871",
    memType: "Passive",
  },
  {
    adNo: 3864,
    name: "Ibrahim Sahl Sha &nbsp;",
    section: "Secondary First Year",
    memNo: "30/383864",
    memType: "Passive",
  },
  {
    adNo: 3858,
    name: "Muhammed Rihan &nbsp;",
    section: "Secondary First Year",
    memNo: "30/383858",
    memType: "Passive",
  },
  {
    adNo: 3865,
    name: "Fasalu Rahman M K &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373865",
    memType: "Passive",
  },
  {
    adNo: 3841,
    name: "Muhammed Adil .K &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373841",
    memType: "Passive",
  },
  {
    adNo: 3842,
    name: "Afthah Muhammed N V &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373842",
    memType: "Passive",
  },
  {
    adNo: 3848,
    name: "Mohammed Hanan",
    section: "Secondary Second Year",
    memNo: "30/373848",
    memType: "Passive",
  },
  {
    adNo: 3859,
    name: "Muhammed Thameem &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373859",
    memType: "Passive",
  },
  {
    adNo: 3875,
    name: "Ajmal Rashad Uvaisi P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373875",
    memType: "Passive",
  },
  {
    adNo: 3883,
    name: "Mohammed Shoubar &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373883",
    memType: "Passive",
  },
  {
    adNo: 3838,
    name: "Muhammed Aamir N &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373838",
    memType: "Passive",
  },
  {
    adNo: 3869,
    name: "Muhammad Rifqathulla",
    section: "Secondary Second Year",
    memNo: "30/373869",
    memType: "Passive",
  },
  {
    adNo: 3867,
    name: "Anwar Muhammad Vp &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373867",
    memType: "Passive",
  },
  {
    adNo: 3882,
    name: "Mohammed Abdulla Arshad&nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373882",
    memType: "Passive",
  },
  {
    adNo: 3866,
    name: "Abdulla Majid P T &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373866",
    memType: "Passive",
  },
  {
    adNo: 3887,
    name: "Muhammed Yaseen Km &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373887",
    memType: "Passive",
  },
  {
    adNo: 3835,
    name: "Muhammed Ashmil K P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373835",
    memType: "Passive",
  },
  {
    adNo: 3837,
    name: "Afeef Nawwas &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373837",
    memType: "Passive",
  },
  {
    adNo: 3857,
    name: "Mohammed Hamdan M P",
    section: "Secondary Second Year",
    memNo: "30/373857",
    memType: "Passive",
  },
  {
    adNo: 3873,
    name: "Muhammed Naseef. T P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373873",
    memType: "Passive",
  },
  {
    adNo: 3836,
    name: "Ahmad Salih .N.K &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373836",
    memType: "Passive",
  },
  {
    adNo: 3880,
    name: "Mohammed Najad Cm &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373880",
    memType: "Passive",
  },
  {
    adNo: 3884,
    name: "Junaid Aboobakcer &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373884",
    memType: "Passive",
  },
  {
    adNo: 3845,
    name: "Sulthan Ibraheem &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373845",
    memType: "Passive",
  },
  {
    adNo: 3860,
    name: "Marsad &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373860",
    memType: "Passive",
  },
  {
    adNo: 3881,
    name: "Mohammed Shadin.Tk &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373881",
    memType: "Passive",
  },
  {
    adNo: 3834,
    name: "Muhammed Shamil V &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373834",
    memType: "Passive",
  },
  {
    adNo: 3843,
    name: "Abdul Haseeb K &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373843",
    memType: "Passive",
  },
  {
    adNo: 3874,
    name: "Muhammed Jaseel K &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373874",
    memType: "Passive",
  },
  {
    adNo: 3743,
    name: "Muhammed Muzammil &nbsp; Mk",
    section: "Secondary Second Year",
    memNo: "30/373743",
    memType: "Passive",
  },
  {
    adNo: 3773,
    name: "Muhammed Salih &nbsp; Pa",
    section: "Secondary Second Year",
    memNo: "30/373773",
    memType: "Passive",
  },
  {
    adNo: 3751,
    name: "Shahabas &nbsp; C",
    section: "Secondary Second Year",
    memNo: "30/373751",
    memType: "Passive",
  },
  {
    adNo: 3767,
    name: "Muhammed Rishad &nbsp; Yp",
    section: "Secondary Second Year",
    memNo: "30/373767",
    memType: "Passive",
  },
  {
    adNo: 3794,
    name: "Ashraf &nbsp; C",
    section: "Secondary Second Year",
    memNo: "30/373794",
    memType: "Passive",
  },
  {
    adNo: 3847,
    name: "Muhammed Amazil &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373847",
    memType: "Passive",
  },
  {
    adNo: 3862,
    name: "Mohamed Najwan C &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373862",
    memType: "Passive",
  },
  {
    adNo: 3839,
    name: "Abdul Hadi Kp &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373839",
    memType: "Passive",
  },
  {
    adNo: 3886,
    name: "Mohammed Adnan C P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373886",
    memType: "Passive",
  },
  {
    adNo: 3890,
    name: "Muhammad Anas",
    section: "Secondary Second Year",
    memNo: "30/373890",
    memType: "Passive",
  },
  {
    adNo: 3888,
    name: "Muhammed Shammas Kp",
    section: "Secondary Second Year",
    memNo: "30/373888",
    memType: "Passive",
  },
  {
    adNo: 3849,
    name: "Muhammedshifan &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373849",
    memType: "Passive",
  },
  {
    adNo: 3855,
    name: "Adhil N.P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373855",
    memType: "Passive",
  },
  {
    adNo: 3852,
    name: "Shammas A &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373852",
    memType: "Passive",
  },
  {
    adNo: 3854,
    name: "Irfan Ahmed P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373854",
    memType: "Passive",
  },
  {
    adNo: 3833,
    name: "Muhammed Arzan Saleem",
    section: "Secondary Second Year",
    memNo: "30/373833",
    memType: "Passive",
  },
  {
    adNo: 3846,
    name: "Muhammed Faheem T &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373846",
    memType: "Passive",
  },
  {
    adNo: 3872,
    name: "Muhammed Sinan P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373872",
    memType: "Passive",
  },
  {
    adNo: 3870,
    name: "Muhammad Nihal C &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373870",
    memType: "Passive",
  },
  {
    adNo: 3851,
    name: "Muhammed Vahid. P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373851",
    memType: "Passive",
  },
  {
    adNo: 3850,
    name: "Sayyid Abdurahman Kps&nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373850",
    memType: "Passive",
  },
  {
    adNo: 3879,
    name: "Muhammad Jalal C.P. &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373879",
    memType: "Passive",
  },
  {
    adNo: 3878,
    name: "Shalafas K C &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373878",
    memType: "Passive",
  },
  {
    adNo: 3889,
    name: "Abdu Samad M &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373889",
    memType: "Passive",
  },
  {
    adNo: 3885,
    name: "Ayman A &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373885",
    memType: "Passive",
  },
  {
    adNo: 3853,
    name: "Mohammed Raazi A &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373853",
    memType: "Passive",
  },
  {
    adNo: 3876,
    name: "Nabeel Ismayeel P &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373876",
    memType: "Passive",
  },
  {
    adNo: 3868,
    name: "Khaleel Al Rahman &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373868",
    memType: "Passive",
  },
  {
    adNo: 3808,
    name: "Ahmed Azim &nbsp;",
    section: "Secondary Second Year",
    memNo: "30/373808",
    memType: "Passive",
  },
  {
    adNo: 3756,
    name: "Muhammed Saalim &nbsp; Kp",
    section: "Secondary Second Year",
    memNo: "30/373756",
    memType: "Passive",
  },
  {
    adNo: 3746,
    name: "Muhammed Hafeez &nbsp; Kaderi",
    section: "Secondary Second Year",
    memNo: "30/373746",
    memType: "Passive",
  },
  {
    adNo: 3757,
    name: "Muhammed Anshad &nbsp; Np",
    section: "Secondary Second Year",
    memNo: "30/373757",
    memType: "Passive",
  },
  {
    adNo: 3745,
    name: "Danish Farheen &nbsp; P",
    section: "Secondary Second Year",
    memNo: "30/373745",
    memType: "Passive",
  },
  {
    adNo: 3803,
    name: "Muhammed Alfan Vf",
    section: "Secondary Second Year",
    memNo: "30/373803",
    memType: "Passive",
  },
  {
    adNo: 3810,
    name: "Muhamed Raihan &nbsp; Mr",
    section: "Secondary Third Year",
    memNo: "30/363810",
    memType: "Passive",
  },
  {
    adNo: 3795,
    name: "Muhammed Jesil Inthisham Pk",
    section: "Secondary Third Year",
    memNo: "30/363795",
    memType: "Passive",
  },
  {
    adNo: 3739,
    name: "Muhammed Adil &nbsp; Mt",
    section: "Secondary Third Year",
    memNo: "30/363739",
    memType: "Passive",
  },
  {
    adNo: 3760,
    name: "Muhammed Safvan &nbsp; Kk",
    section: "Secondary Third Year",
    memNo: "30/363760",
    memType: "Passive",
  },
  {
    adNo: 3783,
    name: "Muhammed Ashmil &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363783",
    memType: "Passive",
  },
  {
    adNo: 3771,
    name: "Muhemmed Murshid &nbsp; P",
    section: "Secondary Third Year",
    memNo: "30/363771",
    memType: "Passive",
  },
  {
    adNo: 3786,
    name: "Amaan Abdul Karim &nbsp; N",
    section: "Secondary Third Year",
    memNo: "30/363786",
    memType: "Passive",
  },
  {
    adNo: 3798,
    name: "Nafih &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363798",
    memType: "Passive",
  },
  {
    adNo: 3749,
    name: "Muhammed Faheem &nbsp; Vm",
    section: "Secondary Third Year",
    memNo: "30/363749",
    memType: "Passive",
  },
  {
    adNo: 3765,
    name: "Muhammed Ibrahimbadusha &nbsp;K",
    section: "Secondary Third Year",
    memNo: "30/363765",
    memType: "Passive",
  },
  {
    adNo: 3733,
    name: "Muhammed Vafi Musthafa &nbsp; Rk",
    section: "Secondary Third Year",
    memNo: "30/363733",
    memType: "Passive",
  },
  {
    adNo: 3784,
    name: "Muhammed Nasim &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363784",
    memType: "Passive",
  },
  {
    adNo: 3738,
    name: "Mohammed Mujthaba &nbsp; Kk",
    section: "Secondary Third Year",
    memNo: "30/363738",
    memType: "Passive",
  },
  {
    adNo: 3804,
    name: "Mustafa Muhammed &nbsp; O",
    section: "Secondary Third Year",
    memNo: "30/363804",
    memType: "Passive",
  },
  {
    adNo: 3801,
    name: "Ahmad Shaheer &nbsp; Ek",
    section: "Secondary Third Year",
    memNo: "30/363801",
    memType: "Passive",
  },
  {
    adNo: 3742,
    name: "Muhammed Uvais &nbsp; N",
    section: "Secondary Third Year",
    memNo: "30/363742",
    memType: "Passive",
  },
  {
    adNo: 3772,
    name: "Muhammed Fahim &nbsp; Kp",
    section: "Secondary Third Year",
    memNo: "30/363772",
    memType: "Passive",
  },
  {
    adNo: 3753,
    name: "Mohammad Shammas &nbsp; Ck",
    section: "Secondary Third Year",
    memNo: "30/363753",
    memType: "Passive",
  },
  {
    adNo: 3782,
    name: "Muhammed Shamil &nbsp; T",
    section: "Secondary Third Year",
    memNo: "30/363782",
    memType: "Passive",
  },
  {
    adNo: 3785,
    name: "Muhammed Ziyad &nbsp; E",
    section: "Secondary Third Year",
    memNo: "30/363785",
    memType: "Passive",
  },
  {
    adNo: 3759,
    name: "Mohamad Anas &nbsp; T",
    section: "Secondary Third Year",
    memNo: "30/363759",
    memType: "Passive",
  },
  {
    adNo: 3779,
    name: "Muhammed Raif &nbsp; Tp",
    section: "Secondary Third Year",
    memNo: "30/363779",
    memType: "Passive",
  },
  {
    adNo: 3736,
    name: "Muhammed Arshad &nbsp; Mp",
    section: "Secondary Third Year",
    memNo: "30/363736",
    memType: "Passive",
  },
  {
    adNo: 3762,
    name: "Hanan Muhammed &nbsp; Mc",
    section: "Secondary Third Year",
    memNo: "30/363762",
    memType: "Passive",
  },
  {
    adNo: 3805,
    name: "Naseemudheen &nbsp; C",
    section: "Secondary Third Year",
    memNo: "30/363805",
    memType: "Passive",
  },
  {
    adNo: 3778,
    name: "Muhammed Irfan &nbsp; Km",
    section: "Secondary Third Year",
    memNo: "30/363778",
    memType: "Passive",
  },
  {
    adNo: 3734,
    name: "Anshif &nbsp; Pp",
    section: "Secondary Third Year",
    memNo: "30/363734",
    memType: "Passive",
  },
  {
    adNo: 3747,
    name: "Muhammed Muslih &nbsp; Cp",
    section: "Secondary Third Year",
    memNo: "30/363747",
    memType: "Passive",
  },
  {
    adNo: 3741,
    name: "Muhammed Afnan &nbsp; Mp",
    section: "Secondary Third Year",
    memNo: "30/363741",
    memType: "Passive",
  },
  {
    adNo: 3776,
    name: "Shiblu Rahman &nbsp; Mt",
    section: "Secondary Third Year",
    memNo: "30/363776",
    memType: "Passive",
  },
  {
    adNo: 3793,
    name: "Mohammed Shahan &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363793",
    memType: "Passive",
  },
  {
    adNo: 3812,
    name: "Muhammed Ajmal &nbsp; Ok",
    section: "Secondary Third Year",
    memNo: "30/363812",
    memType: "Passive",
  },
  {
    adNo: 3679,
    name: "Muhammed Shibili &nbsp; C",
    section: "Secondary Third Year",
    memNo: "30/363679",
    memType: "Passive",
  },
  {
    adNo: 3777,
    name: "Fahmudheen &nbsp; A",
    section: "Secondary Third Year",
    memNo: "30/363777",
    memType: "Passive",
  },
  {
    adNo: 3780,
    name: "Ubaidulla &nbsp; V",
    section: "Secondary Third Year",
    memNo: "30/363780",
    memType: "Passive",
  },
  {
    adNo: 3775,
    name: "Muhammed Shamal &nbsp; T",
    section: "Secondary Third Year",
    memNo: "30/363775",
    memType: "Passive",
  },
  {
    adNo: 3744,
    name: "Muhammed Sabiq &nbsp; P",
    section: "Secondary Third Year",
    memNo: "30/363744",
    memType: "Passive",
  },
  {
    adNo: 3792,
    name: "Muhammed Sinan &nbsp; C",
    section: "Secondary Third Year",
    memNo: "30/363792",
    memType: "Passive",
  },
  {
    adNo: 3797,
    name: "Muhammad Abshar Khan Ak",
    section: "Secondary Third Year",
    memNo: "30/363797",
    memType: "Passive",
  },
  {
    adNo: 3790,
    name: "Muhammed Irfan &nbsp; Kp",
    section: "Secondary Third Year",
    memNo: "30/363790",
    memType: "Passive",
  },
  {
    adNo: 3761,
    name: "Yaseen Bishr &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363761",
    memType: "Passive",
  },
  {
    adNo: 3809,
    name: "Muhammed Munavvar &nbsp; Pp",
    section: "Secondary Third Year",
    memNo: "30/363809",
    memType: "Passive",
  },
  {
    adNo: 3791,
    name: "Shameem &nbsp; M",
    section: "Secondary Third Year",
    memNo: "30/363791",
    memType: "Passive",
  },
  {
    adNo: 3769,
    name: "Ahmad Rabeeh &nbsp; U",
    section: "Secondary Third Year",
    memNo: "30/363769",
    memType: "Passive",
  },
  {
    adNo: 3748,
    name: "Muhammad Fauzan &nbsp; M",
    section: "Secondary Third Year",
    memNo: "30/363748",
    memType: "Passive",
  },
  {
    adNo: 3754,
    name: "Nihal Ahmed &nbsp; N",
    section: "Secondary Third Year",
    memNo: "30/363754",
    memType: "Passive",
  },
  {
    adNo: 3764,
    name: "Mohammed Jinan &nbsp; P",
    section: "Secondary Third Year",
    memNo: "30/363764",
    memType: "Passive",
  },
  {
    adNo: 3758,
    name: "Muhammed Shamil &nbsp; Tp",
    section: "Secondary Third Year",
    memNo: "30/363758",
    memType: "Passive",
  },
  {
    adNo: 3766,
    name: "Muhammed Nihad &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363766",
    memType: "Passive",
  },
  {
    adNo: 3807,
    name: "Sayyid Muhammed Sahal &nbsp; Sv",
    section: "Secondary Third Year",
    memNo: "30/363807",
    memType: "Passive",
  },
  {
    adNo: 3768,
    name: "Muhammed Sabith &nbsp; Pk",
    section: "Secondary Third Year",
    memNo: "30/363768",
    memType: "Passive",
  },
  {
    adNo: 3740,
    name: "Muhammed Bishr &nbsp; Kv",
    section: "Secondary Third Year",
    memNo: "30/363740",
    memType: "Passive",
  },
  {
    adNo: 3750,
    name: "Muhammed Hanan &nbsp; A",
    section: "Secondary Third Year",
    memNo: "30/363750",
    memType: "Passive",
  },
  {
    adNo: 3802,
    name: "Hashim Husain &nbsp; P",
    section: "Secondary Third Year",
    memNo: "30/363802",
    memType: "Passive",
  },
  {
    adNo: 3737,
    name: "Muhammed Jalal &nbsp; Pt",
    section: "Secondary Third Year",
    memNo: "30/363737",
    memType: "Passive",
  },
  {
    adNo: 3796,
    name: "Muhammed Niyas &nbsp; Pk",
    section: "Secondary Third Year",
    memNo: "30/363796",
    memType: "Passive",
  },
  {
    adNo: 3788,
    name: "Shameemul Hasan &nbsp; Tk",
    section: "Secondary Third Year",
    memNo: "30/363788",
    memType: "Passive",
  },
  {
    adNo: 3811,
    name: "Muhammed Hanan &nbsp; Nc",
    section: "Secondary Third Year",
    memNo: "30/363811",
    memType: "Passive",
  },
  {
    adNo: 3787,
    name: "Muhammed Nihal &nbsp; Ma",
    section: "Secondary Third Year",
    memNo: "30/363787",
    memType: "Passive",
  },
  {
    adNo: 3781,
    name: "Muhammed Thameem &nbsp; Nt",
    section: "Secondary Third Year",
    memNo: "30/363781",
    memType: "Passive",
  },
  {
    adNo: 3752,
    name: "Mohammed Midhlaj &nbsp; M",
    section: "Secondary Third Year",
    memNo: "30/363752",
    memType: "Passive",
  },
  {
    adNo: 3763,
    name: "Juman &nbsp;",
    section: "Secondary Third Year",
    memNo: "30/363763",
    memType: "Passive",
  },
  {
    adNo: 3789,
    name: "Muhammed Thoyyib &nbsp; K",
    section: "Secondary Third Year",
    memNo: "30/363789",
    memType: "Passive",
  },
  {
    adNo: 3770,
    name: "Rabeeh Ahammed &nbsp; Ct",
    section: "Secondary Third Year",
    memNo: "30/363770",
    memType: "Passive",
  },
  {
    adNo: 3755,
    name: "Muhammed Favad &nbsp; T",
    section: "Secondary Third Year",
    memNo: "30/363755",
    memType: "Passive",
  },
  {
    adNo: 3677,
    name: "Muhammad Sabeel. P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353677",
    memType: "Active",
  },
  {
    adNo: 3691,
    name: "Mohmed Hashim Ahmed &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353691",
    memType: "Active",
  },
  {
    adNo: 3686,
    name: "Mohammed Abdul Kader &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353686",
    memType: "Active",
  },
  {
    adNo: 3682,
    name: "Muhammed Riswan &nbsp; K",
    section: "Secondary Fourth Year",
    memNo: "30/353682",
    memType: "Active",
  },
  {
    adNo: 3681,
    name: "Mubashir Cp &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353681",
    memType: "Active",
  },
  {
    adNo: 3669,
    name: "Fayiz Mohammed &nbsp; K",
    section: "Secondary Fourth Year",
    memNo: "30/353669",
    memType: "Active",
  },
  {
    adNo: 3668,
    name: "Abdullah Fayis &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353668",
    memType: "Active",
  },
  {
    adNo: 3663,
    name: "Ahammed Rabeeh C P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353663",
    memType: "Active",
  },
  {
    adNo: 3696,
    name: "Sayyid Sadeed Kp &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353696",
    memType: "Active",
  },
  {
    adNo: 3693,
    name: "Muhammed Thamjid C &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353693",
    memType: "Active",
  },
  {
    adNo: 3688,
    name: "Mohammed Aslah &nbsp; Vt",
    section: "Secondary Fourth Year",
    memNo: "30/353688",
    memType: "Active",
  },
  {
    adNo: 3721,
    name: "Muhammed Shameel V &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353721",
    memType: "Active",
  },
  {
    adNo: 3729,
    name: "Sayyid Muhammed Habeeb",
    section: "Secondary Fourth Year",
    memNo: "30/353729",
    memType: "Active",
  },
  {
    adNo: 3708,
    name: "Muhammed Bin Ashraf &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353708",
    memType: "Active",
  },
  {
    adNo: 3724,
    name: "Muhammed Abdul Ali Ok",
    section: "Secondary Fourth Year",
    memNo: "30/353724",
    memType: "Active",
  },
  {
    adNo: 3666,
    name: "Sayyid Shafeef &nbsp; Vp",
    section: "Secondary Fourth Year",
    memNo: "30/353666",
    memType: "Active",
  },
  {
    adNo: 3664,
    name: "Muhammad Javad &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353664",
    memType: "Active",
  },
  {
    adNo: 3715,
    name: "Rinshad K &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353715",
    memType: "Active",
  },
  {
    adNo: 3728,
    name: "Muhammad Razi T &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353728",
    memType: "Active",
  },
  {
    adNo: 3662,
    name: "Mohammed Thakiyudheen &nbsp; L",
    section: "Secondary Fourth Year",
    memNo: "30/353662",
    memType: "Active",
  },
  {
    adNo: 3675,
    name: "Mushthajab C &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353675",
    memType: "Active",
  },
  {
    adNo: 3726,
    name: "Muhammed Shadin Pk &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353726",
    memType: "Active",
  },
  {
    adNo: 3673,
    name: "Hamdh &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353673",
    memType: "Active",
  },
  {
    adNo: 3658,
    name: "Muhammed Sinan &nbsp; V",
    section: "Secondary Fourth Year",
    memNo: "30/353658",
    memType: "Active",
  },
  {
    adNo: 3692,
    name: "Muhammed Shanib Kn &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353692",
    memType: "Active",
  },
  {
    adNo: 3704,
    name: "Muhammed Shafin &nbsp; P",
    section: "Secondary Fourth Year",
    memNo: "30/353704",
    memType: "Active",
  },
  {
    adNo: 3670,
    name: "Mohammed Sidhan &nbsp; Kp",
    section: "Secondary Fourth Year",
    memNo: "30/353670",
    memType: "Active",
  },
  {
    adNo: 3697,
    name: "Muhammed Dilshad. K &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353697",
    memType: "Active",
  },
  {
    adNo: 3712,
    name: "Muhammed Farhan Cs &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353712",
    memType: "Active",
  },
  {
    adNo: 3690,
    name: "Muhammed Ameen &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353690",
    memType: "Active",
  },
  {
    adNo: 3683,
    name: "Muhammed Adnan &nbsp; M",
    section: "Secondary Fourth Year",
    memNo: "30/353683",
    memType: "Active",
  },
  {
    adNo: 3674,
    name: "Muhammed Rafi K.S &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353674",
    memType: "Active",
  },
  {
    adNo: 3678,
    name: "Muhammed Razi &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353678",
    memType: "Active",
  },
  {
    adNo: 3640,
    name: "Muhammed Abdulla C &nbsp; C",
    section: "Secondary Fourth Year",
    memNo: "30/353640",
    memType: "Active",
  },
  {
    adNo: 3508,
    name: "Muhammed Muflih &nbsp; N",
    section: "Secondary Fourth Year",
    memNo: "30/353508",
    memType: "Active",
  },
  {
    adNo: 3727,
    name: "Muhammed Kashif Minhaj",
    section: "Secondary Fourth Year",
    memNo: "30/353727",
    memType: "Active",
  },
  {
    adNo: 3707,
    name: "Mohammed Shammas T &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353707",
    memType: "Active",
  },
  {
    adNo: 3719,
    name: "Aqlas Dhanil &nbsp; Mk",
    section: "Secondary Fourth Year",
    memNo: "30/353719",
    memType: "Active",
  },
  {
    adNo: 3667,
    name: "Muhammed Rabeeh Mt &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353667",
    memType: "Active",
  },
  {
    adNo: 3580,
    name: "Muhammed Rinshad &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353580",
    memType: "Active",
  },
  {
    adNo: 3680,
    name: "Abdul Hayy &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353680",
    memType: "Active",
  },
  {
    adNo: 3732,
    name: "Muhammed Shamil &nbsp; V",
    section: "Secondary Fourth Year",
    memNo: "30/353732",
    memType: "Active",
  },
  {
    adNo: 3711,
    name: "Muhammed Rabeeh M &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353711",
    memType: "Active",
  },
  {
    adNo: 3706,
    name: "Ahammade Shoucky &nbsp; Tk",
    section: "Secondary Fourth Year",
    memNo: "30/353706",
    memType: "Active",
  },
  {
    adNo: 3659,
    name: "Muhammed Adhil &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353659",
    memType: "Active",
  },
  {
    adNo: 3699,
    name: "Muhammed Faheem &nbsp; C",
    section: "Secondary Fourth Year",
    memNo: "30/353699",
    memType: "Active",
  },
  {
    adNo: 3701,
    name: "Muhammed Aslah A P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353701",
    memType: "Active",
  },
  {
    adNo: 3676,
    name: "Muhammed Hani M &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353676",
    memType: "Active",
  },
  {
    adNo: 3661,
    name: "Muhammed Nufais &nbsp; Tp",
    section: "Secondary Fourth Year",
    memNo: "30/353661",
    memType: "Active",
  },
  {
    adNo: 3717,
    name: "Muhammed Shihan &nbsp; Vp",
    section: "Secondary Fourth Year",
    memNo: "30/353717",
    memType: "Active",
  },
  {
    adNo: 3702,
    name: "Mohammed Raees &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353702",
    memType: "Active",
  },
  {
    adNo: 3654,
    name: "Ansil Rahman &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353654",
    memType: "Active",
  },
  {
    adNo: 3684,
    name: "Sayyid Mohamed Avvab",
    section: "Secondary Fourth Year",
    memNo: "30/353684",
    memType: "Active",
  },
  {
    adNo: 3694,
    name: "Ahamed Ishan O P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353694",
    memType: "Active",
  },
  {
    adNo: 3718,
    name: "Sinan V &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353718",
    memType: "Active",
  },
  {
    adNo: 3722,
    name: "Muhammed Haseeb &nbsp; Ch",
    section: "Secondary Fourth Year",
    memNo: "30/353722",
    memType: "Active",
  },
  {
    adNo: 3705,
    name: "Mohammed Arshad M K &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353705",
    memType: "Active",
  },
  {
    adNo: 3720,
    name: "Amal Mafaz &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353720",
    memType: "Active",
  },
  {
    adNo: 3714,
    name: "Muhammed Sinan &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353714",
    memType: "Active",
  },
  {
    adNo: 3602,
    name: "Mohammed Semeel Kt",
    section: "Secondary Fourth Year",
    memNo: "30/353602",
    memType: "Active",
  },
  {
    adNo: 3598,
    name: "Muhammed Afnan &nbsp; Kp",
    section: "Secondary Fourth Year",
    memNo: "30/353598",
    memType: "Active",
  },
  {
    adNo: 3672,
    name: "Muhammed Niyas K &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353672",
    memType: "Active",
  },
  {
    adNo: 3709,
    name: "Muhammed Azhar &nbsp; Mv",
    section: "Secondary Fourth Year",
    memNo: "30/353709",
    memType: "Active",
  },
  {
    adNo: 3700,
    name: "Muhammed Nasl M &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353700",
    memType: "Active",
  },
  {
    adNo: 3689,
    name: "Mashar Hussain Ap &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353689",
    memType: "Active",
  },
  {
    adNo: 3730,
    name: "Adeeb Hussain Ka &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353730",
    memType: "Active",
  },
  {
    adNo: 3723,
    name: "Muhammed Nabhan &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353723",
    memType: "Active",
  },
  {
    adNo: 3665,
    name: "Muhammed Risil.K &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353665",
    memType: "Active",
  },
  {
    adNo: 3725,
    name: "Adhnan &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353725",
    memType: "Active",
  },
  {
    adNo: 3618,
    name: "Muhammed Rabeeh &nbsp; Kp",
    section: "Secondary Fourth Year",
    memNo: "30/353618",
    memType: "Active",
  },
  {
    adNo: 3695,
    name: "Mohamed Ihsan P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353695",
    memType: "Active",
  },
  {
    adNo: 3656,
    name: "Naseef V &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353656",
    memType: "Active",
  },
  {
    adNo: 3713,
    name: "Muhammed &nbsp; O",
    section: "Secondary Fourth Year",
    memNo: "30/353713",
    memType: "Active",
  },
  {
    adNo: 3588,
    name: "Muhammed Muhsin &nbsp; Ap",
    section: "Secondary Fourth Year",
    memNo: "30/353588",
    memType: "Active",
  },
  {
    adNo: 3685,
    name: "Muhammed Sidan &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353685",
    memType: "Active",
  },
  {
    adNo: 3716,
    name: "Muhammad Muzzammil P",
    section: "Secondary Fourth Year",
    memNo: "30/353716",
    memType: "Active",
  },
  {
    adNo: 3655,
    name: "Muhammed Nishan &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353655",
    memType: "Active",
  },
  {
    adNo: 3657,
    name: "Muhammed Aflah C &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353657",
    memType: "Active",
  },
  {
    adNo: 3710,
    name: "Amjed Muhammed K.P &nbsp;",
    section: "Secondary Fourth Year",
    memNo: "30/353710",
    memType: "Active",
  },
  {
    adNo: 3594,
    name: "Mohammed Naeem &nbsp; Vk",
    section: "Secondary Fourth Year",
    memNo: "30/353594",
    memType: "Active",
  },
  {
    adNo: 3592,
    name: "Zuhair P.P &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343592",
    memType: "Active",
  },
  {
    adNo: 3587,
    name: "Muhammed Nawas",
    section: "Secondary Final Year",
    memNo: "30/343587",
    memType: "Active",
  },
  {
    adNo: 3623,
    name: "Muhammed Anas &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343623",
    memType: "Active",
  },
  {
    adNo: 3593,
    name: "Nishdan &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343593",
    memType: "Active",
  },
  {
    adNo: 3595,
    name: "Ahammed Al Sabith",
    section: "Secondary Final Year",
    memNo: "30/343595",
    memType: "Active",
  },
  {
    adNo: 3621,
    name: "Abu Thahir &nbsp; Ea",
    section: "Secondary Final Year",
    memNo: "30/343621",
    memType: "Active",
  },
  {
    adNo: 3601,
    name: "Salman &nbsp; K",
    section: "Secondary Final Year",
    memNo: "30/343601",
    memType: "Active",
  },
  {
    adNo: 3604,
    name: "Mohammed Sinan &nbsp; M",
    section: "Secondary Final Year",
    memNo: "30/343604",
    memType: "Active",
  },
  {
    adNo: 3634,
    name: "Suvailim &nbsp; Kk",
    section: "Secondary Final Year",
    memNo: "30/343634",
    memType: "Active",
  },
  {
    adNo: 3571,
    name: "Muhammed Anshed &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343571",
    memType: "Active",
  },
  {
    adNo: 3637,
    name: "Qamar-Ul-Zaman &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343637",
    memType: "Active",
  },
  {
    adNo: 3607,
    name: "Muhammed Hashim &nbsp; K",
    section: "Secondary Final Year",
    memNo: "30/343607",
    memType: "Active",
  },
  {
    adNo: 3506,
    name: "Muhammed Nabeel &nbsp; Mp",
    section: "Secondary Final Year",
    memNo: "30/343506",
    memType: "Active",
  },
  {
    adNo: 3610,
    name: "Ali Sabith &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343610",
    memType: "Active",
  },
  {
    adNo: 3613,
    name: "Muhammed Muhsin &nbsp; V",
    section: "Secondary Final Year",
    memNo: "30/343613",
    memType: "Active",
  },
  {
    adNo: 3631,
    name: "Mohammed Hasan &nbsp; Cp",
    section: "Secondary Final Year",
    memNo: "30/343631",
    memType: "Active",
  },
  {
    adNo: 3570,
    name: "Muhammed Shamnad &nbsp; T",
    section: "Secondary Final Year",
    memNo: "30/343570",
    memType: "Active",
  },
  {
    adNo: 3576,
    name: "Muhammed Razin &nbsp; Cm",
    section: "Secondary Final Year",
    memNo: "30/343576",
    memType: "Active",
  },
  {
    adNo: 3603,
    name: "Muhammed Nabeel &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343603",
    memType: "Active",
  },
  {
    adNo: 3643,
    name: "Fuad &nbsp; A",
    section: "Secondary Final Year",
    memNo: "30/343643",
    memType: "Active",
  },
  {
    adNo: 3599,
    name: "Ahammed Shabeeb &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343599",
    memType: "Active",
  },
  {
    adNo: 3449,
    name: "Muhammed Ajzal K &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343449",
    memType: "Active",
  },
  {
    adNo: 3596,
    name: "Muhammed Azmil &nbsp; K",
    section: "Secondary Final Year",
    memNo: "30/343596",
    memType: "Active",
  },
  {
    adNo: 3641,
    name: "Muhammed Rashid &nbsp; M",
    section: "Secondary Final Year",
    memNo: "30/343641",
    memType: "Active",
  },
  {
    adNo: 3521,
    name: "Muhammed Ashfaque &nbsp; Ct",
    section: "Secondary Final Year",
    memNo: "30/343521",
    memType: "Active",
  },
  {
    adNo: 3629,
    name: "Muhammed Muzzammil &nbsp; Kc",
    section: "Secondary Final Year",
    memNo: "30/343629",
    memType: "Active",
  },
  {
    adNo: 3581,
    name: "Mohammed Nihal Thameem",
    section: "Secondary Final Year",
    memNo: "30/343581",
    memType: "Active",
  },
  {
    adNo: 3644,
    name: "Muhammed Bishr",
    section: "Secondary Final Year",
    memNo: "30/343644",
    memType: "Active",
  },
  {
    adNo: 3625,
    name: "Ameen Ahsan &nbsp; Pt",
    section: "Secondary Final Year",
    memNo: "30/343625",
    memType: "Active",
  },
  {
    adNo: 3444,
    name: "Mahshooq Rahman &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343444",
    memType: "Active",
  },
  {
    adNo: 3617,
    name: "Eyaas Umer &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343617",
    memType: "Active",
  },
  {
    adNo: 3474,
    name: "Muhammed Nishal &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343474",
    memType: "Active",
  },
  {
    adNo: 3509,
    name: "Muhammed Musfir &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343509",
    memType: "Active",
  },
  {
    adNo: 3445,
    name: "Salman &nbsp; Faris",
    section: "Secondary Final Year",
    memNo: "30/343445",
    memType: "Active",
  },
  {
    adNo: 3502,
    name: "Mohammed Shamil &nbsp; Kt",
    section: "Secondary Final Year",
    memNo: "30/343502",
    memType: "Active",
  },
  {
    adNo: 3591,
    name: "Muhammed Anas &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343591",
    memType: "Active",
  },
  {
    adNo: 3608,
    name: "Ahemed Jaseel &nbsp; K",
    section: "Secondary Final Year",
    memNo: "30/343608",
    memType: "Active",
  },
  {
    adNo: 3583,
    name: "Muhammed Fadhil &nbsp; V.P",
    section: "Secondary Final Year",
    memNo: "30/343583",
    memType: "Active",
  },
  {
    adNo: 3612,
    name: "Mohammed Jasim Kabeer",
    section: "Secondary Final Year",
    memNo: "30/343612",
    memType: "Active",
  },
  {
    adNo: 3620,
    name: "Muhammed Niyas &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343620",
    memType: "Active",
  },
  {
    adNo: 3574,
    name: "Basim Sulaiman &nbsp; Kappil",
    section: "Secondary Final Year",
    memNo: "30/343574",
    memType: "Active",
  },
  {
    adNo: 3630,
    name: "Fazalu Rahman &nbsp; Ka",
    section: "Secondary Final Year",
    memNo: "30/343630",
    memType: "Active",
  },
  {
    adNo: 3586,
    name: "Muhammed Nihal &nbsp; V",
    section: "Secondary Final Year",
    memNo: "30/343586",
    memType: "Active",
  },
  {
    adNo: 3575,
    name: "Muhammed Dilshad &nbsp; Kp",
    section: "Secondary Final Year",
    memNo: "30/343575",
    memType: "Active",
  },
  {
    adNo: 3616,
    name: "Muhammed Fasil P &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343616",
    memType: "Active",
  },
  {
    adNo: 3639,
    name: "Muhammed Mufeed &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343639",
    memType: "Active",
  },
  {
    adNo: 3624,
    name: "Shihan Muhammed &nbsp; Kk",
    section: "Secondary Final Year",
    memNo: "30/343624",
    memType: "Active",
  },
  {
    adNo: 3635,
    name: "Muhammed Mubashir &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343635",
    memType: "Active",
  },
  {
    adNo: 3577,
    name: "Ibraheem Bhadusha &nbsp; Ek",
    section: "Secondary Final Year",
    memNo: "30/343577",
    memType: "Active",
  },
  {
    adNo: 3562,
    name: "Muhammed Jiyad &nbsp; Cp",
    section: "Secondary Final Year",
    memNo: "30/343562",
    memType: "Active",
  },
  {
    adNo: 3638,
    name: "Muhammed Muflih &nbsp; Ap",
    section: "Secondary Final Year",
    memNo: "30/343638",
    memType: "Active",
  },
  {
    adNo: 3642,
    name: "Muhammed Abdul Basith &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343642",
    memType: "Active",
  },
  {
    adNo: 3611,
    name: "Muhammed Shahan &nbsp; Ap",
    section: "Secondary Final Year",
    memNo: "30/343611",
    memType: "Active",
  },
  {
    adNo: 3500,
    name: "Muhammed Musthafa &nbsp; C",
    section: "Secondary Final Year",
    memNo: "30/343500",
    memType: "Active",
  },
  {
    adNo: 3600,
    name: "Danish Dinshad &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343600",
    memType: "Active",
  },
  {
    adNo: 3584,
    name: "Muhammed Fasil &nbsp; Vp",
    section: "Secondary Final Year",
    memNo: "30/343584",
    memType: "Active",
  },
  {
    adNo: 3553,
    name: "Sayyid Muhammed Hashir&nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343553",
    memType: "Active",
  },
  {
    adNo: 3585,
    name: "Mujeeb Rahman &nbsp; Kv",
    section: "Secondary Final Year",
    memNo: "30/343585",
    memType: "Active",
  },
  {
    adNo: 3578,
    name: "Muhammed Afnan &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343578",
    memType: "Active",
  },
  {
    adNo: 3622,
    name: "Mohammed Rabeeh &nbsp; Ck",
    section: "Secondary Final Year",
    memNo: "30/343622",
    memType: "Active",
  },
  {
    adNo: 3606,
    name: "Muhammed Swalih &nbsp; Ck",
    section: "Secondary Final Year",
    memNo: "30/343606",
    memType: "Active",
  },
  {
    adNo: 3636,
    name: "Muhammed Shamil &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343636",
    memType: "Active",
  },
  {
    adNo: 3626,
    name: "Muhammed Muhsin &nbsp; Kv",
    section: "Secondary Final Year",
    memNo: "30/343626",
    memType: "Active",
  },
  {
    adNo: 3556,
    name: "Muhammed Abdul Vajid T &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343556",
    memType: "Active",
  },
  {
    adNo: 3579,
    name: "Muhammed Haseeb &nbsp; P.T",
    section: "Secondary Final Year",
    memNo: "30/343579",
    memType: "Active",
  },
  {
    adNo: 3615,
    name: "Muhammed Nihal &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343615",
    memType: "Active",
  },
  {
    adNo: 3590,
    name: "Muhammed Rizwan &nbsp;",
    section: "Secondary Final Year",
    memNo: "30/343590",
    memType: "Active",
  },
  {
    adNo: 3567,
    name: "Muhammed Abdullah Swalih Tt",
    section: "Secondary Final Year",
    memNo: "30/343567",
    memType: "Active",
  },
  {
    adNo: 3544,
    name: "Midlaj &nbsp; P",
    section: "Secondary Final Year",
    memNo: "30/343544",
    memType: "Active",
  },
  {
    adNo: 3503,
    name: "Sinan &nbsp; Ck",
    section: "Senior Secondary First Year",
    memNo: "30/333503",
    memType: "Active",
  },
  {
    adNo: 3530,
    name: "Muhammed Ashim K &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333530",
    memType: "Active",
  },
  {
    adNo: 3507,
    name: "Mohammed Roshan &nbsp; K",
    section: "Senior Secondary First Year",
    memNo: "30/333507",
    memType: "Active",
  },
  {
    adNo: 3542,
    name: "Muhammed Rinshad &nbsp; Nk",
    section: "Senior Secondary First Year",
    memNo: "30/333542",
    memType: "Active",
  },
  {
    adNo: 3535,
    name: "Mohammed Hashim &nbsp; Pp",
    section: "Senior Secondary First Year",
    memNo: "30/333535",
    memType: "Active",
  },
  {
    adNo: 3551,
    name: "Muhammed Nafil &nbsp; A",
    section: "Senior Secondary First Year",
    memNo: "30/333551",
    memType: "Active",
  },
  {
    adNo: 3517,
    name: "Muhammed Sinan T &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333517",
    memType: "Active",
  },
  {
    adNo: 3527,
    name: "Salmanul Faris &nbsp; Pv",
    section: "Senior Secondary First Year",
    memNo: "30/333527",
    memType: "Active",
  },
  {
    adNo: 3504,
    name: "Muhammed Niyas &nbsp; Kt",
    section: "Senior Secondary First Year",
    memNo: "30/333504",
    memType: "Active",
  },
  {
    adNo: 3513,
    name: "Muhammed Anshid &nbsp; Kt",
    section: "Senior Secondary First Year",
    memNo: "30/333513",
    memType: "Active",
  },
  {
    adNo: 3550,
    name: "Yamin Ali &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333550",
    memType: "Active",
  },
  {
    adNo: 3536,
    name: "Azeem Abdu Rahman &nbsp; Kv",
    section: "Senior Secondary First Year",
    memNo: "30/333536",
    memType: "Active",
  },
  {
    adNo: 3555,
    name: "Muhammed Rishad Vp &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333555",
    memType: "Active",
  },
  {
    adNo: 3569,
    name: "Muhammed Hashim A &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333569",
    memType: "Active",
  },
  {
    adNo: 3501,
    name: "Sufyan Mk &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333501",
    memType: "Active",
  },
  {
    adNo: 3505,
    name: "Muhammed Razi &nbsp; Mp",
    section: "Senior Secondary First Year",
    memNo: "30/333505",
    memType: "Active",
  },
  {
    adNo: 3511,
    name: "Adeeb Ahammed &nbsp; Nk",
    section: "Senior Secondary First Year",
    memNo: "30/333511",
    memType: "Active",
  },
  {
    adNo: 3423,
    name: "Younus &nbsp; Pk",
    section: "Senior Secondary First Year",
    memNo: "30/333423",
    memType: "Active",
  },
  {
    adNo: 3568,
    name: "Muhammed Sinan &nbsp; Kp",
    section: "Senior Secondary First Year",
    memNo: "30/333568",
    memType: "Active",
  },
  {
    adNo: 3525,
    name: "Ahmed Sahl &nbsp; N",
    section: "Senior Secondary First Year",
    memNo: "30/333525",
    memType: "Active",
  },
  {
    adNo: 3538,
    name: "Sobahul Bishar &nbsp; Pk",
    section: "Senior Secondary First Year",
    memNo: "30/333538",
    memType: "Active",
  },
  {
    adNo: 3411,
    name: "Sayyid Shaham Ap &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333411",
    memType: "Active",
  },
  {
    adNo: 3456,
    name: "Salman Nasooh",
    section: "Senior Secondary First Year",
    memNo: "30/333456",
    memType: "Active",
  },
  {
    adNo: 3492,
    name: "Mohammed Shamil E",
    section: "Senior Secondary First Year",
    memNo: "30/333492",
    memType: "Active",
  },
  {
    adNo: 3540,
    name: "Abdul Vahid Mt",
    section: "Senior Secondary First Year",
    memNo: "30/333540",
    memType: "Active",
  },
  {
    adNo: 3522,
    name: "Mohammed Jaseer Vc",
    section: "Senior Secondary First Year",
    memNo: "30/333522",
    memType: "Active",
  },
  {
    adNo: 3519,
    name: "Muhammed Munawar &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333519",
    memType: "Active",
  },
  {
    adNo: 3552,
    name: "Ihsan &nbsp; Kv",
    section: "Senior Secondary First Year",
    memNo: "30/333552",
    memType: "Active",
  },
  {
    adNo: 3448,
    name: "Muhammed Fawaz &nbsp; Cp",
    section: "Senior Secondary First Year",
    memNo: "30/333448",
    memType: "Active",
  },
  {
    adNo: 3548,
    name: "Mehsil Farsan &nbsp; Vm",
    section: "Senior Secondary First Year",
    memNo: "30/333548",
    memType: "Active",
  },
  {
    adNo: 3516,
    name: "Mohammed Hisham &nbsp; Kk",
    section: "Senior Secondary First Year",
    memNo: "30/333516",
    memType: "Active",
  },
  {
    adNo: 3563,
    name: "Shaheem K &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333563",
    memType: "Active",
  },
  {
    adNo: 3564,
    name: "Muhammed Suhail Vt &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333564",
    memType: "Active",
  },
  {
    adNo: 3514,
    name: "Muhammed Nishan &nbsp; Vk",
    section: "Senior Secondary First Year",
    memNo: "30/333514",
    memType: "Active",
  },
  {
    adNo: 3554,
    name: "Muhammed Mubarack &nbsp; A",
    section: "Senior Secondary First Year",
    memNo: "30/333554",
    memType: "Active",
  },
  {
    adNo: 3565,
    name: "Muhammed Sahl &nbsp; Vt",
    section: "Senior Secondary First Year",
    memNo: "30/333565",
    memType: "Active",
  },
  {
    adNo: 3529,
    name: "Muhammed Shahid &nbsp; C",
    section: "Senior Secondary First Year",
    memNo: "30/333529",
    memType: "Active",
  },
  {
    adNo: 3543,
    name: "Muhammed Jisar &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333543",
    memType: "Active",
  },
  {
    adNo: 3515,
    name: "Muhammed Rimnas &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333515",
    memType: "Active",
  },
  {
    adNo: 3558,
    name: "Muhammed Farhan &nbsp; Cp",
    section: "Senior Secondary First Year",
    memNo: "30/333558",
    memType: "Active",
  },
  {
    adNo: 3534,
    name: "Hannoof &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333534",
    memType: "Active",
  },
  {
    adNo: 3518,
    name: "Hasan Muhammad &nbsp; V",
    section: "Senior Secondary First Year",
    memNo: "30/333518",
    memType: "Active",
  },
  {
    adNo: 3531,
    name: "Muhammed Farshin &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333531",
    memType: "Active",
  },
  {
    adNo: 3561,
    name: "Muhammed Sinan &nbsp; P",
    section: "Senior Secondary First Year",
    memNo: "30/333561",
    memType: "Active",
  },
  {
    adNo: 3392,
    name: "Fadhi Muhammed &nbsp; Cp",
    section: "Senior Secondary First Year",
    memNo: "30/333392",
    memType: "Active",
  },
  {
    adNo: 3473,
    name: "Ali Sinan &nbsp;",
    section: "Senior Secondary First Year",
    memNo: "30/333473",
    memType: "Active",
  },
  {
    adNo: 3572,
    name: "Muhammed Noorul Ameen",
    section: "Senior Secondary First Year",
    memNo: "30/333572",
    memType: "Active",
  },
  {
    adNo: 3491,
    name: "Javad Muhsin &nbsp; Pk",
    section: "Senior Secondary First Year",
    memNo: "30/333491",
    memType: "Active",
  },
  {
    adNo: 3547,
    name: "Muhammed Mufleh M",
    section: "Senior Secondary First Year",
    memNo: "30/333547",
    memType: "Active",
  },
  {
    adNo: 3431,
    name: "Muhammed Sabeel Pk",
    section: "Senior Secondary First Year",
    memNo: "30/333431",
    memType: "Active",
  },
  {
    adNo: 3478,
    name: "Muhammed Rebin &nbsp; M",
    section: "Senior Secondary First Year",
    memNo: "30/333478",
    memType: "Active",
  },{
    adNo: "3012",
    name: "Muhammed Hussain",
    section: "Degree Final Year",
    memNo: "30/293012",
  },
  {
    adNo: "3014",
    name: "Muhammed Favvaz P",
    section: "Degree Final Year",
    memNo: "30/293014",
  },
  {
    adNo: "2947",
    name: "Muhammed Murshid A",
    section: "Degree Final Year",
    memNo: "30/292947",
  },
  {
    adNo: "2844",
    name: "Muhammed Shaheer Ak",
    section: "Degree Final Year",
    memNo: "30/292844",
  },
  {
    adNo: "2951",
    name: "Muhammed Fasil T",
    section: "Degree Final Year",
    memNo: "30/292951",
  },
  {
    adNo: "2946",
    name: "Shuhaib A",
    section: "Degree Final Year",
    memNo: "30/292946",
  },
  {
    adNo: "2976",
    name: "Mohammed Siraj Ap",
    section: "Degree Final Year",
    memNo: "30/292976",
  },
  {
    adNo: "2975",
    name: "Muhammed Fuad Mp",
    section: "Degree Final Year",
    memNo: "30/292975",
  },
  {
    adNo: "2963",
    name: "Muhammed Sadique",
    section: "Degree Final Year",
    memNo: "30/292963",
  },
  {
    adNo: "2983",
    name: "Ramil A Backer Mr",
    section: "Degree Final Year",
    memNo: "30/292983",
  },
  {
    adNo: "3015",
    name: "Athhar Jahan",
    section: "Degree Final Year",
    memNo: "30/293015",
  },
  {
    adNo: "2980",
    name: "Mohamed Irfan",
    section: "Degree Final Year",
    memNo: "30/292980",
  },
  {
    adNo: "2931",
    name: "Muhammed Rabeeh M",
    section: "Degree Final Year",
    memNo: "30/292931",
  },
  {
    adNo: "2933",
    name: "Mohammed Afthab",
    section: "Degree Final Year",
    memNo: "30/292933",
  },
  {
    adNo: "3001",
    name: "Mohammed Arshad",
    section: "Degree Final Year",
    memNo: "30/293001",
  },
  {
    adNo: "2993",
    name: "Muhammed Swalih",
    section: "Degree Final Year",
    memNo: "30/292993",
  },
  {
    adNo: "3401",
    name: "Muhammed Ali A",
    section: "Degree Final Year",
    memNo: "30/293401",
  },
  {
    adNo: "2957",
    name: "Najmudheen C",
    section: "Degree Final Year",
    memNo: "30/292957",
  },
  {
    adNo: "2974",
    name: "Muhammed Jasim Muneer Cp",
    section: "Degree Final Year",
    memNo: "30/292974",
  },
  {
    adNo: "3010",
    name: "Muhammed Munavir",
    section: "Degree Final Year",
    memNo: "30/293010",
  },
  {
    adNo: "2960",
    name: "Mohamed Zakariya Ps",
    section: "Degree Final Year",
    memNo: "30/292960",
  },
  {
    adNo: "3404",
    name: "Mohammed Anas An",
    section: "Degree Final Year",
    memNo: "30/293404",
  },
  {
    adNo: "2941",
    name: "Mohammed Afsal K",
    section: "Degree Final Year",
    memNo: "30/292941",
  },
  {
    adNo: "2979",
    name: "Muhammed Abdul Hakeem",
    section: "Degree Final Year",
    memNo: "30/292979",
  },
  {
    adNo: "3004",
    name: "Swalih",
    section: "Degree Final Year",
    memNo: "30/293004",
  },
  {
    adNo: "2956",
    name: "Khalid",
    section: "Degree Final Year",
    memNo: "30/292956",
  },
  {
    adNo: "2982",
    name: "Anshif Shaheen Vp",
    section: "Degree Final Year",
    memNo: "30/292982",
  },
  {
    adNo: "2950",
    name: "Mohamed Sabith",
    section: "Degree Final Year",
    memNo: "30/292950",
  },
  {
    adNo: "2969",
    name: "Muhammed Junaid P",
    section: "Degree Final Year",
    memNo: "30/292969",
  },
  {
    adNo: "2958",
    name: "Salmanul Faris Kt",
    section: "Degree Final Year",
    memNo: "30/292958",
  },
  {
    adNo: "3017",
    name: "Muhammed Raees Mk",
    section: "Degree Final Year",
    memNo: "30/293017",
  },
  {
    adNo: "2981",
    name: "Mohammed Siyadh A",
    section: "Degree Final Year",
    memNo: "30/292981",
  },
  {
    adNo: "2966",
    name: "Mohamed Shakeeb",
    section: "Degree Final Year",
    memNo: "30/292966",
  },
  {
    adNo: "2992",
    name: "Ibrahim Badusha C",
    section: "Degree Final Year",
    memNo: "30/292992",
  },
  {
    adNo: "2944",
    name: "Adil Samnas",
    section: "Degree Final Year",
    memNo: "30/292944",
  },
  {
    adNo: "2973",
    name: "Abdul Haseeb K",
    section: "Degree Final Year",
    memNo: "30/292973",
  },
  {
    adNo: "2970",
    name: "Muhammad Shareef Mk",
    section: "Degree Final Year",
    memNo: "30/292970",
  },
  {
    adNo: "2998",
    name: "Muhammed Sahal",
    section: "Degree Final Year",
    memNo: "30/292998",
  },
  {
    adNo: "2954",
    name: "Mohammed Sanif P",
    section: "Degree Final Year",
    memNo: "30/292954",
  },
  {
    adNo: "2990",
    name: "Ahmed Shafeeque",
    section: "Degree Final Year",
    memNo: "30/292990",
  },
  {
    adNo: "2991",
    name: "Sadhique",
    section: "Degree Final Year",
    memNo: "30/292991",
  },
  {
    adNo: "3009",
    name: "Fadil Mohyudheen",
    section: "Degree Final Year",
    memNo: "30/293009",
  },
  {
    adNo: "2936",
    name: "Mohammed Razi Tk",
    section: "Degree Final Year",
    memNo: "30/292936",
  },
  {
    adNo: "2978",
    name: "Sayyid Ahammed Razi Kn",
    section: "Degree Final Year",
    memNo: "30/292978",
  },
  {
    adNo: "2959",
    name: "Muhammed Shahin Pk",
    section: "Degree Final Year",
    memNo: "30/292959",
  },
  {
    adNo: "3003",
    name: "Muhammed Muhsin",
    section: "Degree Final Year",
    memNo: "30/293003",
  },
  {
    adNo: "3011",
    name: "Muhmad Muzammil M",
    section: "Degree Final Year",
    memNo: "30/293011",
  },
  {
    adNo: "2996",
    name: "Muhammad Baheej Kt",
    section: "Degree Final Year",
    memNo: "30/292996",
  },
  {
    adNo: "2953",
    name: "Ajsal Kt",
    section: "Degree Final Year",
    memNo: "30/292953",
  },
  {
    adNo: "2972",
    name: "Muhammed Favaz A",
    section: "Degree Final Year",
    memNo: "30/292972",
  },
  {
    adNo: "3008",
    name: "Muhmmed Iqbal Tt",
    section: "Degree Final Year",
    memNo: "30/293008",
  },
  {
    adNo: "3353",
    name: "Muhammed Sinan K",
    section: "Degree First Year",
    memNo: "30/313353",
  },
  {
    adNo: "3328",
    name: "Muhammed Bujair C P",
    section: "Degree First Year",
    memNo: "30/313328",
  },
  {
    adNo: "3365",
    name: "Muhammed Basil C",
    section: "Degree First Year",
    memNo: "30/313365",
  },
  {
    adNo: "3312",
    name: "Muhammed Dilshad A",
    section: "Degree First Year",
    memNo: "30/313312",
  },
  {
    adNo: "3316",
    name: "Jamshid K",
    section: "Degree First Year",
    memNo: "30/313316",
  },
  {
    adNo: "3171",
    name: "Abdul Basith V",
    section: "Degree First Year",
    memNo: "30/313171",
  },
  {
    adNo: "3310",
    name: "Muzammil Siddique",
    section: "Degree First Year",
    memNo: "30/313310",
  },
  {
    adNo: "3350",
    name: "Abdul Basith Pk",
    section: "Degree First Year",
    memNo: "30/313350",
  },
  {
    adNo: "3896",
    name: "Muhammed Rasil C",
    section: "Degree First Year",
    memNo: "30/313896",
  },
  {
    adNo: "3372",
    name: "Muhammed Theshreef",
    section: "Degree First Year",
    memNo: "30/313372",
  },
  {
    adNo: "3343",
    name: "Jamnas Muhammed Pc",
    section: "Degree First Year",
    memNo: "30/313343",
  },
  {
    adNo: "3369",
    name: "Abdullah Al Mubarak",
    section: "Degree First Year",
    memNo: "30/313369",
  },
  {
    adNo: "3331",
    name: "Farsin Vp",
    section: "Degree First Year",
    memNo: "30/313331",
  },
  {
    adNo: "3314",
    name: "Mohammed Afsal Ap",
    section: "Degree First Year",
    memNo: "30/313314",
  },
  {
    adNo: "3366",
    name: "Muhammed Afzal Kv",
    section: "Degree First Year",
    memNo: "30/313366",
  },
  {
    adNo: "3364",
    name: "Subhan V",
    section: "Degree First Year",
    memNo: "30/313364",
  },
  {
    adNo: "3371",
    name: "Shameel",
    section: "Degree First Year",
    memNo: "30/313371",
  },
  {
    adNo: "3653",
    name: "Muhammed Luquman A",
    section: "Degree First Year",
    memNo: "30/313653",
  },
  {
    adNo: "3383",
    name: "Muhammed Ishaque K",
    section: "Degree First Year",
    memNo: "30/313383",
  },
  {
    adNo: "3347",
    name: "Muhammed Riyan P",
    section: "Degree First Year",
    memNo: "30/313347",
  },
  {
    adNo: "3322",
    name: "Muhammad Anas U",
    section: "Degree First Year",
    memNo: "30/313322",
  },
  {
    adNo: "3351",
    name: "Mohammed Salih P",
    section: "Degree First Year",
    memNo: "30/313351",
  },
  {
    adNo: "3340",
    name: "Sahadudheen M",
    section: "Degree First Year",
    memNo: "30/313340",
  },
  {
    adNo: "3325",
    name: "Anvar Hussain Ms",
    section: "Degree First Year",
    memNo: "30/313325",
  },
  {
    adNo: "3315",
    name: "Muhammed Jasir K",
    section: "Degree First Year",
    memNo: "30/313315",
  },
  {
    adNo: "3894",
    name: "Muhammed Nasweeh",
    section: "Degree First Year",
    memNo: "30/313894",
  },
  {
    adNo: "3360",
    name: "Muhammad Rabeeh Kt",
    section: "Degree First Year",
    memNo: "30/313360",
  },
  {
    adNo: "3373",
    name: "Muhammed Mufeed",
    section: "Degree First Year",
    memNo: "30/313373",
  },
  {
    adNo: "3165",
    name: "Muhammed Nufais",
    section: "Degree First Year",
    memNo: "30/313165",
  },
  {
    adNo: "3377",
    name: "Muhammed Adil K",
    section: "Degree First Year",
    memNo: "30/313377",
  },
  {
    adNo: "3309",
    name: "Muhammed Shabeeb Tp",
    section: "Degree First Year",
    memNo: "30/313309",
  },
  {
    adNo: "3897",
    name: "Mohammed Salih P",
    section: "Degree First Year",
    memNo: "30/313897",
  },
  {
    adNo: "3324",
    name: "Nihal Muhamed Vp",
    section: "Degree First Year",
    memNo: "30/313324",
  },
  {
    adNo: "3352",
    name: "Muhammed Thenshir",
    section: "Degree First Year",
    memNo: "30/313352",
  },
  {
    adNo: "3892",
    name: "Muhammed Mannah Ca",
    section: "Degree First Year",
    memNo: "30/313892",
  },
  {
    adNo: "3151",
    name: "Mohammed Munavvir",
    section: "Degree First Year",
    memNo: "30/313151",
  },
  {
    adNo: "3359",
    name: "Muhammed Jafin Tvc",
    section: "Degree First Year",
    memNo: "30/313359",
  },
  {
    adNo: "3320",
    name: "Muhammed Sinan P",
    section: "Degree First Year",
    memNo: "30/313320",
  },
  {
    adNo: "3898",
    name: "Salmanul Faris K",
    section: "Degree First Year",
    memNo: "30/313898",
  },
  {
    adNo: "3319",
    name: "Muhammed Nizam C.H",
    section: "Degree First Year",
    memNo: "30/313319",
  },
  {
    adNo: "3355",
    name: "Abdunnafih Mp",
    section: "Degree First Year",
    memNo: "30/313355",
  },
  {
    adNo: "3390",
    name: "Muhammed Inshad K",
    section: "Degree First Year",
    memNo: "30/313390",
  },
  {
    adNo: "2962",
    name: "Mohammed Musthajab",
    section: "Degree First Year",
    memNo: "30/312962",
  },
  {
    adNo: "3388",
    name: "Muhammed Ya'Qoob P",
    section: "Degree First Year",
    memNo: "30/313388",
  },
  {
    adNo: "3345",
    name: "Muhammed Ameer",
    section: "Degree First Year",
    memNo: "30/313345",
  },
  {
    adNo: "2949",
    name: "Muhammed Swalih Pp",
    section: "Degree First Year",
    memNo: "30/312949",
  },
  {
    adNo: "3329",
    name: "Abdul Malik Kc",
    section: "Degree First Year",
    memNo: "30/313329",
  },
  {
    adNo: "3374",
    name: "Muhammed Zulfikar",
    section: "Degree First Year",
    memNo: "30/313374",
  },
  {
    adNo: "3317",
    name: "Mohammed Sabith M",
    section: "Degree First Year",
    memNo: "30/313317",
  },
  {
    adNo: "3125",
    name: "Saifudheen Mt",
    section: "Degree First Year",
    memNo: "30/313125",
  },
  {
    adNo: "3308",
    name: "Abdul Bari Nc",
    section: "Degree First Year",
    memNo: "30/313308",
  },
  {
    adNo: "3370",
    name: "Muhammed Abdu Rahman",
    section: "Degree First Year",
    memNo: "30/313370",
  },
  {
    adNo: "3341",
    name: "Muhammed Shabeeb Kk",
    section: "Degree First Year",
    memNo: "30/313341",
  },
  {
    adNo: "3381",
    name: "Muhamed Ihsan N",
    section: "Degree First Year",
    memNo: "30/313381",
  },
  {
    adNo: "3891",
    name: "Muhammad Sahal Tk",
    section: "Degree First Year",
    memNo: "30/313891",
  },
  {
    adNo: "3348",
    name: "Mohammed Nihal P",
    section: "Degree First Year",
    memNo: "30/313348",
  },
  {
    adNo: "3326",
    name: "Muhammad Raoof",
    section: "Degree First Year",
    memNo: "30/313326",
  },
  {
    adNo: "3379",
    name: "Muhammed Thanseer",
    section: "Degree First Year",
    memNo: "30/313379",
  },
  {
    adNo: "3361",
    name: "Mohammed Swalih K",
    section: "Degree First Year",
    memNo: "30/313361",
  },
  {
    adNo: "3895",
    name: "Muhammed Nihal Ok",
    section: "Degree First Year",
    memNo: "30/313895",
  },
  {
    adNo: "3645",
    name: "Mohammed Ashiq As",
    section: "Degree Second Year",
    memNo: "30/303645",
  },
  {
    adNo: "3158",
    name: "Nazim Ali Mohamed Ka",
    section: "Degree Second Year",
    memNo: "30/303158",
  },
  {
    adNo: "3185",
    name: "Shamil Kc",
    section: "Degree Second Year",
    memNo: "30/303185",
  },
  {
    adNo: "3161",
    name: "Muhammed Munawar Pt",
    section: "Degree Second Year",
    memNo: "30/303161",
  },
  {
    adNo: "2945",
    name: "Ya'Qoob A",
    section: "Degree Second Year",
    memNo: "30/302945",
  },
  {
    adNo: "2999",
    name: "Muhammed Ansas Ip",
    section: "Degree Second Year",
    memNo: "30/302999",
  },
  {
    adNo: "3831",
    name: "Sahed Cp",
    section: "Degree Second Year",
    memNo: "30/303831",
  },
  {
    adNo: "3135",
    name: "Basith Mahmood Pc",
    section: "Degree Second Year",
    memNo: "30/303135",
  },
  {
    adNo: "3647",
    name: "Muhammed Bilal N",
    section: "Degree Second Year",
    memNo: "30/303647",
  },
  {
    adNo: "3129",
    name: "Muhammed Mirshad K",
    section: "Degree Second Year",
    memNo: "30/303129",
  },
  {
    adNo: "3646",
    name: "Naseehudheen S",
    section: "Degree Second Year",
    memNo: "30/303646",
  },
  {
    adNo: "3821",
    name: "Muhammed Adnan B",
    section: "Degree Second Year",
    memNo: "30/303821",
  },
  {
    adNo: "3180",
    name: "Midlaj P",
    section: "Degree Second Year",
    memNo: "30/303180",
  },
  {
    adNo: "3132",
    name: "Muhammed Unais K",
    section: "Degree Second Year",
    memNo: "30/303132",
  },
  {
    adNo: "3195",
    name: "Muhammed Raoof",
    section: "Degree Second Year",
    memNo: "30/303195",
  },
  {
    adNo: "3177",
    name: "Muhammed Abdul Basith",
    section: "Degree Second Year",
    memNo: "30/303177",
  },
  {
    adNo: "3202",
    name: "Jouhar Jahan K",
    section: "Degree Second Year",
    memNo: "30/303202",
  },
  {
    adNo: "3127",
    name: "Muhammed Ajnan P",
    section: "Degree Second Year",
    memNo: "30/303127",
  },
  {
    adNo: "3141",
    name: "Muhammed Rashid At",
    section: "Degree Second Year",
    memNo: "30/303141",
  },
  {
    adNo: "3169",
    name: "Muhammad Rishad Mt",
    section: "Degree Second Year",
    memNo: "30/303169",
  },
  {
    adNo: "2935",
    name: "Muzammil Pm",
    section: "Degree Second Year",
    memNo: "30/302935",
  },
  {
    adNo: "3191",
    name: "Rashid Abdul Azeez A",
    section: "Degree Second Year",
    memNo: "30/303191",
  },
  {
    adNo: "2964",
    name: "Muhammed Adil C",
    section: "Degree Second Year",
    memNo: "30/302964",
  },
  {
    adNo: "3149",
    name: "Salman Faris Abdussalam P",
    section: "Degree Second Year",
    memNo: "30/303149",
  },
  {
    adNo: "3181",
    name: "Muhammed Shabeeb M",
    section: "Degree Second Year",
    memNo: "30/303181",
  },
  {
    adNo: "3200",
    name: "Mohammed Samnoon M",
    section: "Degree Second Year",
    memNo: "30/303200",
  },
  {
    adNo: "2934",
    name: "Muhammed Nihal I",
    section: "Degree Second Year",
    memNo: "30/302934",
  },
  {
    adNo: "3652",
    name: "Bilal Muhammeed A",
    section: "Degree Second Year",
    memNo: "30/303652",
  },
  {
    adNo: "3126",
    name: "Muhammed Althaf Pk",
    section: "Degree Second Year",
    memNo: "30/303126",
  },
  {
    adNo: "3174",
    name: "Muhammed Rasmil Ct",
    section: "Degree Second Year",
    memNo: "30/303174",
  },
  {
    adNo: "3128",
    name: "Muhammed Niyas Kp",
    section: "Degree Second Year",
    memNo: "30/303128",
  },
  {
    adNo: "3818",
    name: "Hafiz Jamal Ej",
    section: "Degree Second Year",
    memNo: "30/303818",
  },
  {
    adNo: "3816",
    name: "Ameer Suhail K",
    section: "Degree Second Year",
    memNo: "30/303816",
  },
  {
    adNo: "2948",
    name: "Muhammed Ameer C",
    section: "Degree Second Year",
    memNo: "30/302948",
  },
  {
    adNo: "3162",
    name: "Fayizul Hasan Ak",
    section: "Degree Second Year",
    memNo: "30/303162",
  },
  {
    adNo: "3204",
    name: "Muhammed Althaf Aa",
    section: "Degree Second Year",
    memNo: "30/303204",
  },
  {
    adNo: "3143",
    name: "Nashbil Ahammed Km",
    section: "Degree Second Year",
    memNo: "30/303143",
  },
  {
    adNo: "3822",
    name: "Muhammed Aflah Kk",
    section: "Degree Second Year",
    memNo: "30/303822",
  },
  {
    adNo: "3829",
    name: "Muhammed Thoufeeq Et",
    section: "Degree Second Year",
    memNo: "30/303829",
  },
  {
    adNo: "3196",
    name: "Mubashir T",
    section: "Degree Second Year",
    memNo: "30/303196",
  },
  {
    adNo: "3192",
    name: "Muhammad Jaseer T",
    section: "Degree Second Year",
    memNo: "30/303192",
  },
  {
    adNo: "3815",
    name: "Althaf Ali P",
    section: "Degree Second Year",
    memNo: "30/303815",
  },
  {
    adNo: "3186",
    name: "Mohmmed Shibili K",
    section: "Degree Second Year",
    memNo: "30/303186",
  },
  {
    adNo: "2968",
    name: "Mohammed Afsal",
    section: "Degree Second Year",
    memNo: "30/302968",
  },
  {
    adNo: "3827",
    name: "Muhammed Shafeeq T",
    section: "Degree Second Year",
    memNo: "30/303827",
  },
  {
    adNo: "3199",
    name: "Muhammed Swalih M",
    section: "Degree Second Year",
    memNo: "30/303199",
  },
  {
    adNo: "3190",
    name: "Abdulla Sinan T",
    section: "Degree Second Year",
    memNo: "30/303190",
  },
  {
    adNo: "3651",
    name: "Faizal A",
    section: "Degree Second Year",
    memNo: "30/303651",
  },
  {
    adNo: "2997",
    name: "Muhammed Sahal Mk",
    section: "Degree Second Year",
    memNo: "30/302997",
  },
  {
    adNo: "3826",
    name: "Muhammed Naseel M",
    section: "Degree Second Year",
    memNo: "30/303826",
  },
  {
    adNo: "3153",
    name: "Abdul Raoof",
    section: "Degree Second Year",
    memNo: "30/303153",
  },
  {
    adNo: "3650",
    name: "Sharafath Ms",
    section: "Degree Second Year",
    memNo: "30/303650",
  },
  {
    adNo: "3194",
    name: "Muhamed Aslam Farhan U",
    section: "Degree Second Year",
    memNo: "30/303194",
  },
  {
    adNo: "3138",
    name: "Muhammed Janish Nehyan P",
    section: "Degree Second Year",
    memNo: "30/303138",
  },
  {
    adNo: "3183",
    name: "Badusha Ta",
    section: "Degree Second Year",
    memNo: "30/303183",
  },
  {
    adNo: "3168",
    name: "Irshad P",
    section: "Degree Second Year",
    memNo: "30/303168",
  },
  {
    adNo: "3131",
    name: "Mohammed Mishab Mp",
    section: "Degree Second Year",
    memNo: "30/303131",
  },
  {
    adNo: "3187",
    name: "Muhammed Sinan K",
    section: "Degree Second Year",
    memNo: "30/303187",
  },
  {
    adNo: "3139",
    name: "Muhammed Shibli C",
    section: "Degree Second Year",
    memNo: "30/303139",
  },
  {
    adNo: "3813",
    name: "Abdulla K",
    section: "Degree Second Year",
    memNo: "30/303813",
  },
  {
    adNo: "3198",
    name: "Nawwaf V",
    section: "Degree Second Year",
    memNo: "30/303198",
  },
  {
    adNo: "3140",
    name: "Aboobacker Shad",
    section: "Degree Second Year",
    memNo: "30/303140",
  },
  {
    adNo: "3641",
    name: "Abdulla A",
    section: "Degree Second Year",
    memNo: "30/303641",
  },
  {
    adNo: "3814",
    name: "Afsal K",
    section: "Degree Second Year",
    memNo: "30/303814",
  },
  {
    adNo: "3825",
    name: "Muhammed Junaid Kv",
    section: "Degree Second Year",
    memNo: "30/303825",
  },
  {
    adNo: "3144",
    name: "Muhammed Fayis Pv",
    section: "Degree Second Year",
    memNo: "30/303144",
  },
  {
    adNo: "2828",
    name: "Muhammed Farhan P",
    section: "Degree Second Year",
    memNo: "30/302828",
  },
  {
    adNo: "3832",
    name: "Ziyad Tp",
    section: "Degree Second Year",
    memNo: "30/303832",
  },
  {
    adNo: "3156",
    name: "Muhammed Naseef Kp",
    section: "Degree Second Year",
    memNo: "30/303156",
  },
  {
    adNo: "3648",
    name: "Swabir H",
    section: "Degree Second Year",
    memNo: "30/303648",
  },
  {
    adNo: "3820",
    name: "Muhammed Junaid Kk",
    section: "Degree Second Year",
    memNo: "30/303820",
  },
  {
    adNo: "3424",
    name: "Majid Pk",
    section: "Senior Secondary Final Year",
    memNo: "30/323424",
  },
  {
    adNo: "3451",
    name: "Muhammed Shamir T",
    section: "Senior Secondary Final Year",
    memNo: "30/323451",
  },
  {
    adNo: "3367",
    name: "Shareef T",
    section: "Senior Secondary Final Year",
    memNo: "30/323367",
  },
  {
    adNo: "3464",
    name: "Muhammed Afsal N",
    section: "Senior Secondary Final Year",
    memNo: "30/323464",
  },
  {
    adNo: "3441",
    name: "Fahmeed Khan Ep",
    section: "Senior Secondary Final Year",
    memNo: "30/323441",
  },
  {
    adNo: "3490",
    name: "Fawaz Muhammed Vs",
    section: "Senior Secondary Final Year",
    memNo: "30/323490",
  },
  {
    adNo: "3382",
    name: "Amjad Moosa Pk",
    section: "Senior Secondary Final Year",
    memNo: "30/323382",
  },
  {
    adNo: "3430",
    name: "Mohammed Muzammil E",
    section: "Senior Secondary Final Year",
    memNo: "30/323430",
  },
  {
    adNo: "3450",
    name: "Ahmad Razi Pt",
    section: "Senior Secondary Final Year",
    memNo: "30/323450",
  },
  {
    adNo: "3433",
    name: "Muhammed Swadiq",
    section: "Senior Secondary Final Year",
    memNo: "30/323433",
  },
  {
    adNo: "3432",
    name: "Muhammed Midlaj Av",
    section: "Senior Secondary Final Year",
    memNo: "30/323432",
  },
  {
    adNo: "3358",
    name: "Muhammed Farhan Ev",
    section: "Senior Secondary Final Year",
    memNo: "30/323358",
  },
  {
    adNo: "3485",
    name: "Muhammed Muflih K",
    section: "Senior Secondary Final Year",
    memNo: "30/323485",
  },
  {
    adNo: "3468",
    name: "Labeeb Sp",
    section: "Senior Secondary Final Year",
    memNo: "30/323468",
  },
  {
    adNo: "3346",
    name: "Muhammed Nihal Pa",
    section: "Senior Secondary Final Year",
    memNo: "30/323346",
  },
  {
    adNo: "3436",
    name: "Muhammed Shibili A",
    section: "Senior Secondary Final Year",
    memNo: "30/323436",
  },
  {
    adNo: "3418",
    name: "Abdulla Sinan Pt",
    section: "Senior Secondary Final Year",
    memNo: "30/323418",
  },
  {
    adNo: "3414",
    name: "Muhammed Hisham Ac",
    section: "Senior Secondary Final Year",
    memNo: "30/323414",
  },
  {
    adNo: "3447",
    name: "Muhammed Nufail Kp",
    section: "Senior Secondary Final Year",
    memNo: "30/323447",
  },
  {
    adNo: "3457",
    name: "Muhammed Sufyan Mp",
    section: "Senior Secondary Final Year",
    memNo: "30/323457",
  },
  {
    adNo: "3426",
    name: "Muhammed Nazeeb N",
    section: "Senior Secondary Final Year",
    memNo: "30/323426",
  },
  {
    adNo: "3428",
    name: "Muhammed Sinan Kt",
    section: "Senior Secondary Final Year",
    memNo: "30/323428",
  },
  {
    adNo: "3416",
    name: "Swalih Minhaj U",
    section: "Senior Secondary Final Year",
    memNo: "30/323416",
  },
  {
    adNo: "3336",
    name: "Mohammed Maflooh K",
    section: "Senior Secondary Final Year",
    memNo: "30/323336",
  },
  {
    adNo: "3476",
    name: "Jishil K",
    section: "Senior Secondary Final Year",
    memNo: "30/323476",
  },
  {
    adNo: "3342",
    name: "Nahid K",
    section: "Senior Secondary Final Year",
    memNo: "30/323342",
  },
  {
    adNo: "3461",
    name: "Sayyid Miqdad Hasani P",
    section: "Senior Secondary Final Year",
    memNo: "30/323461",
  },
  {
    adNo: "3417",
    name: "Midhlaj Pm",
    section: "Senior Secondary Final Year",
    memNo: "30/323417",
  },
  {
    adNo: "3376",
    name: "Muhammed Nabeel Np",
    section: "Senior Secondary Final Year",
    memNo: "30/323376",
  },
  {
    adNo: "3440",
    name: "Muhammed Aslam Vt",
    section: "Senior Secondary Final Year",
    memNo: "30/323440",
  },
  {
    adNo: "3460",
    name: "Javad Ahmad Bilal P",
    section: "Senior Secondary Final Year",
    memNo: "30/323460",
  },
  {
    adNo: "3484",
    name: "Mohammed Aslam Kv",
    section: "Senior Secondary Final Year",
    memNo: "30/323484",
  },
  {
    adNo: "3321",
    name: "Muhammed Dilfas Pt",
    section: "Senior Secondary Final Year",
    memNo: "30/323321",
  },
  {
    adNo: "3415",
    name: "Arshad Mp",
    section: "Senior Secondary Final Year",
    memNo: "30/323415",
  },
  {
    adNo: "3453",
    name: "Muhammed Habeeb",
    section: "Senior Secondary Final Year",
    memNo: "30/323453",
  },
  {
    adNo: "3483",
    name: "Mohammed Rabeeh P",
    section: "Senior Secondary Final Year",
    memNo: "30/323483",
  },
  {
    adNo: "3427",
    name: "Ashmil Ashraf Kp",
    section: "Senior Secondary Final Year",
    memNo: "30/323427",
  },
  {
    adNo: "3344",
    name: "Mohammed Ramshad U",
    section: "Senior Secondary Final Year",
    memNo: "30/323344",
  },
  {
    adNo: "3420",
    name: "Abdul Basith Vp",
    section: "Senior Secondary Final Year",
    memNo: "30/323420",
  },
  {
    adNo: "3412",
    name: "Sayyid Muhammed Miqdad Jifri",
    section: "Senior Secondary Final Year",
    memNo: "30/323412",
  },
  {
    adNo: "3439",
    name: "Muhammed Sahl Pp",
    section: "Senior Secondary Final Year",
    memNo: "30/323439",
  },
  {
    adNo: "3409",
    name: "Muhammed Irfan K",
    section: "Senior Secondary Final Year",
    memNo: "30/323409",
  },
  {
    adNo: "3410",
    name: "Muhammed Masroor P",
    section: "Senior Secondary Final Year",
    memNo: "30/323410",
  },
  {
    adNo: "3471",
    name: "Muhammed Shammas",
    section: "Senior Secondary Final Year",
    memNo: "30/323471",
  },
  {
    adNo: "3419",
    name: "Farhan C",
    section: "Senior Secondary Final Year",
    memNo: "30/323419",
  },
  {
    adNo: "3363",
    name: "Muhammed Rabeeh K",
    section: "Senior Secondary Final Year",
    memNo: "30/323363",
  },
  {
    adNo: "3452",
    name: "Muhammed Nafeel",
    section: "Senior Secondary Final Year",
    memNo: "30/323452",
  },
  {
    adNo: "3437",
    name: "Muhammed Shakeeb T",
    section: "Senior Secondary Final Year",
    memNo: "30/323437",
  },
  {
    adNo: "3442",
    name: "Abdul Raoof Ca",
    section: "Senior Secondary Final Year",
    memNo: "30/323442",
  },
  {
    adNo: "3463",
    name: "Munawir Ali K",
    section: "Senior Secondary Final Year",
    memNo: "30/323463",
  },
  {
    adNo: "3323",
    name: "Mohammed Rabeeh P",
    section: "Senior Secondary Final Year",
    memNo: "30/323323",
  },
  {
    adNo: "3475",
    name: "Ahmad Shameem Kp",
    section: "Senior Secondary Final Year",
    memNo: "30/323475",
  },
  {
    adNo: "3465",
    name: "Muhammed Midlaj Ms",
    section: "Senior Secondary Final Year",
    memNo: "30/323465",
  },
  {
    adNo: "3206",
    name: "Muhammed Junaid Kt",
    section: "Senior Secondary Final Year",
    memNo: "30/323206",
  },
  {
    adNo: "3422",
    name: "Abdul Muhaimin Pt",
    section: "Senior Secondary Final Year",
    memNo: "30/323422",
  },
  {
    adNo: "3470",
    name: "Mohammed Raees K",
    section: "Senior Secondary Final Year",
    memNo: "30/323470",
  },
  {
    adNo: "3467",
    name: "Muhammed Naseeh Mc",
    section: "Senior Secondary Final Year",
    memNo: "30/323467",
  },
  {
    adNo: "3458",
    name: "Muhammed Bisher Kc",
    section: "Senior Secondary Final Year",
    memNo: "30/323458",
  },
  {
    adNo: "3481",
    name: "Minhaj P",
    section: "Senior Secondary Final Year",
    memNo: "30/323481",
  },
];

let filterData = (key) => {
  let dataInfo = document.querySelector(".dataInfo");
  // Matching Data
  let finalData = studentData.filter((value) => value.section == key);
  // returns Complete Database is `$key` Doesn't Exsist
  if (!key) {
    finalData = studentData;
    dataInfo.style.opacity = "0";
  } else {
    dataInfo.style.opacity = "1";
  }

  // Creating HTML
  let layout = "";
  finalData.forEach(({ name, adNo, section, memNo, memType }) => {
    layout += `<div class="id_front">
    <div class="hadi_dot"></div>
            <div class="data_header">
                <p class="heading">Member Identity Card</p>
                <p class="isActive">${memType} Member</p>
                </div>
            <div class="id_data">
                <div class="id_image" id="image"
                    style="background:red url('./data/img/${
                      section + "/" + adNo
                    }.jpg')" alt="Student Image"></div>
                <p class="name_adNo_container">
                    <span class="name_container">Name: <span class="name">${name}</span> </span>
                    <span class="adNo_container">Ad.No: <span class="adNo">${adNo}</span> </span>
                    </p>
                <p class="section_container">Section: <span class="section">${section}</span> </p>
                <div class="data_footer">
                    <p class="ValidDate_container">Valid Upto: <span class="section">07-06-2023</span> </p>
                    <p class="memNo_container">Membership Number: <span class="memNo">${memNo}</span> </p>
                </div>
            </div>
        </div>`;
  });

  // Printing HTML
  document.querySelector("main").innerHTML = layout;

  // Printing Info
  let myInfo = document.querySelector(".info");
  let newInfo = `
  <table>
    <tr class="filteredData">
    <th>Filtered Data:</th>
    <td>${finalData.length}</td>
    </tr>
    <tr>
    <th>Filtering By:</th>
    <td>${key}</td>
    </tr>
    <tr class="totalData">
      <th>Total Data:</th>
      <td>${studentData.length}</td>
    </tr>
  </table>`;

  myInfo.innerHTML = newInfo;
};

filterData();

filterButton();
